### ISSUE TITLE
RuntimeError: Cannot find callable deit_base_patch16_224 in hubconf

### ISSUE THREAD

**Issue by LiuHaoChina** [facebookresearch/deit#136]
I don't know what happened, but I reported an error when using the deit in torch hub：
`model = torch.hub.load('facebookresearch/deit:main', 'deit_base_patch16_224', pretrained=True)`

It was still available an hour ago. I saw you modify the branch content. I don't know whether it has anything to do with the modified content.

Traceback (most recent call last):
  File "D:\编译器\pycharm\PyCharm 2019.1.1\helpers\pydev\pydevd.py", line 1741, in <module>
    main()
  File "D:\编译器\pycharm\PyCharm 2019.1.1\helpers\pydev\pydevd.py", line 1735, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "D:\编译器\pycharm\PyCharm 2019.1.1\helpers\pydev\pydevd.py", line 1135, in run
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\编译器\pycharm\PyCharm 2019.1.1\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "F:/Project/sdjs2021/test.py", line 100, in <module>
    main()
  File "F:/Project/sdjs2021/test.py", line 57, in main
    model = torch.hub.load('facebookresearch/deit:main', 'deit_base_patch16_224', pretrained=True)
  File "F:\anaconda\anaconda3.7\envs\pytorch-18-python36\lib\site-packages\torch\hub.py", line 370, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "F:\anaconda\anaconda3.7\envs\pytorch-18-python36\lib\site-packages\torch\hub.py", line 398, in _load_local
    entry = _load_entry_from_hubconf(hub_module, model)
  File "F:\anaconda\anaconda3.7\envs\pytorch-18-python36\lib\site-packages\torch\hub.py", line 218, in _load_entry_from_hubconf
    raise RuntimeError('Cannot find callable {} in hubconf'.format(model))
RuntimeError: Cannot find callable deit_base_patch16_224 in hubconf

**Comment by TouvronHugo** [comment]
Hi @LiuHaoChina,
I have restored the file as before. I will investigate where the issue comes from.
Best,
Hugo

**Comment by kanji95** [comment]
Same issue here, `torch.hub.load` works in python shell but this exception is raised when I call it from a python script.

**Comment by GerogeD** [comment]
Hi,How did you solve this problem，I'm having the same issue，I found that there really is no model needed in hubconf，Can you help me? Thank you so much

transformer = torch.hub.load('facebookresearch/deit:main', 'deit_tiny_distilled_patch16_224', pretrained=True)

Traceback (most recent call last):
  File "/home/common-dir/HX_code/PANet/Pri_train.py", line 429, in <module>
    main()
  File "/home/common-dir/HX_code/PANet/Pri_train.py", line 128, in main
    leaky=use_leaky, norm=norm_type).to(device)
  File "/home/common-dir/HX_code/PANet/models/networks.py", line 282, in __init__
    transformer = torch.hub.load('facebookresearch/deit:main', 'deit_tiny_distilled_patch16_224')
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/torch/hub.py", line 370, in load
    model = _load_local(repo_or_dir, model, *args, **kwargs)
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/torch/hub.py", line 398, in _load_local
    entry = _load_entry_from_hubconf(hub_module, model)
  File "/root/miniconda3/envs/py37/lib/python3.7/site-packages/torch/hub.py", line 218, in _load_entry_from_hubconf
    raise RuntimeError('Cannot find callable {} in hubconf'.format(model))
RuntimeError: Cannot find callable deit_tiny_distilled_patch16_224 in hubconf
