### ISSUE TITLE
unexpected keyword argument 'pretrained_cfg'

### ISSUE THREAD

**Issue by entron** [facebookresearch/deit#212]
I am testing the package with newer version of pytorch and timm as pytorch=1.7 is no longer availabe with simple pip install. The software version I am using are:

```
Python=3.10.9
pytorch=1.3.1
timm=0.6.12
```

When I run this command:

```
python main.py --model deit_small_patch16_LS --data-path /data/IMAGES/IMAGENET/ --batch 256 --lr 4e-3 --epochs 800 --weight-decay 0.05 --sched cosine --input-size 224 --eval-crop-ratio 1.0 --reprob 0.0 --smoothing 0.0 --warmup-epochs 5 --drop 0.0 --seed 0 --opt fusedlamb --warmup-lr 1e-6 --mixup .8 --drop-path 0.05 --cutmix 1.0 --unscale-lr  --color-jitter 0.3 --ThreeAugment
```
I got the following error:

```
Creating model: deit_small_patch16_LS
Traceback (most recent call last):
  File "/home/entron/work/deit/main.py", line 485, in <module>
    main(args)
  File "/home/entron/work/deit/main.py", line 259, in main
    model = create_model(
  File "/home/entron/miniconda3/envs/deit/lib/python3.10/site-packages/timm/models/factory.py", line 71, in create_model
    model = create_fn(pretrained=pretrained, pretrained_cfg=pretrained_cfg, **kwargs)
  File "/home/entron/work/deit/models_v2.py", line 282, in deit_small_patch16_LS
    model = vit_models(
TypeError: vit_models.__init__() got an unexpected keyword argument 'pretrained_cfg'
```
It looks like the code is not compatibal with newer verision of timm. Could someone give me some guidance how to make it work?

**Comment by MohitIntel** [comment]
I saw similar problem. Try passing pretrained_cfg=None as parameter in the definition of deit_small_patch16_LS .
