### ISSUE TITLE
RuntimeError: No shared folder available

### ISSUE THREAD

**Issue by pawopawo** [facebookresearch/deit#30]
Traceback (most recent call last):
File "run_with_submitit.py", line 130, in
main()
File "run_with_submitit.py", line 89, in main
args.job_dir = get_shared_folder() / "%j"
File "run_with_submitit.py", line 40, in get_shared_folder
raise RuntimeError("No shared folder available")
RuntimeError: No shared folder available

**Comment by RechelTeamo** [comment]
What do you do to solve this question? I meet the same problem.
thank u

**Comment by zhang-shuwen** [comment]
How to save this problem? I meet the same one. Thank u
