### ISSUE TITLE
NCCL error

### ISSUE THREAD

**Issue by normster** [facebookresearch/deit#5]
Thanks for the code release!

I tried to launch a run on submitit + slurm with the default parameters (`python run_with_submitit.py`) and after a couple epochs the job died with the following error in one of the 16 processes and wasn't automatically restarted:

```
Traceback (most recent call last):
  File "/private/home/norm/miniconda3/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/private/home/norm/miniconda3/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/private/home/norm/miniconda3/lib/python3.8/site-packages/submitit/core/_submit.py", line 11, in <module>
    submitit_main()
  File "/private/home/norm/miniconda3/lib/python3.8/site-packages/submitit/core/submission.py", line 65, in submitit_main
    process_job(args.folder)
  File "/private/home/norm/miniconda3/lib/python3.8/site-packages/submitit/core/submission.py", line 58, in process_job
    raise error
  File "/private/home/norm/miniconda3/lib/python3.8/site-packages/submitit/core/submission.py", line 47, in process_job
    result = delayed.result()
  File "/private/home/norm/miniconda3/lib/python3.8/site-packages/submitit/core/utils.py", line 123, in result
    self._result = self.function(*self.args, **self.kwargs)
  File "run_with_submitit.py", line 60, in __call__
    classification.main(self.args)
  File "/private/home/norm/code/deit/main.py", line 165, in main
    utils.init_distributed_mode(args)
  File "/private/home/norm/code/deit/utils.py", line 243, in init_distributed_mode
    torch.distributed.init_process_group(backend=args.dist_backend, init_method=args.dist_url,
  File "/private/home/norm/miniconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 455, in init_process_group
    barrier()
  File "/private/home/norm/miniconda3/lib/python3.8/site-packages/torch/distributed/distributed_c10d.py", line 1960, in barrier
    work = _default_pg.barrier()
RuntimeError: NCCL error in: /opt/conda/conda-bld/pytorch_1607370117127/work/torch/lib/c10d/ProcessGroupNCCL.cpp:784, unhandled system error, NCCL version 2.7.8
```

I re-ran the job manually and it seems to be doing fine now, but did you ever run into this error? How did you fix this?

**Comment by fmassa** [comment]
Hi,

This could indicate one of the nodes was for some reason irresponsive during the distributed initialization.

In order to debug those types of errors, I generally use the environment variable `NCCL_DEBUG=INFO` to get more information about what's going on within NCCL.

So if you get those errors more regularly, could you please run the script with
```
NCCL_DEBUG=INFO python run_with_submitit.py
```
and share the full logs?

Given that I believe this was a one-off error I'm closing this issue, but please let us know if you keep facing this problem.
