### ISSUE TITLE
OSError: cannot identify image file <_io.BufferedReader name=imagenet/raw-data/train/n01667778/n01667778_6494.JPEG'

### ISSUE THREAD

**Issue by Jxu-Thu** [facebookresearch/deit#76]
2021-03-10T13:17:11.883Z: [1,0]<stdout>:Epoch: [2]  [ 150/1251]  eta: 0:20:52  lr: 0.000201  loss: 6.8610 (6.8841)  time: 1.0552  data: 0.0035  max mem: 8249
2021-03-10T13:17:22.096Z: [1,0]<stdout>:Epoch: [2]  [ 160/1251]  eta: 0:20:33  lr: 0.000201  loss: 6.8604 (6.8833)  time: 1.0350  data: 0.0027  max mem: 8249
2021-03-10T13:17:32.869Z: [1,0]<stdout>:Epoch: [2]  [ 170/1251]  eta: 0:20:17  lr: 0.000201  loss: 6.8637 (6.8823)  time: 1.0378  data: 0.0019  max mem: 8249
2021-03-10T13:17:42.892Z: [1,0]<stdout>:Epoch: [2]  [ 180/1251]  eta: 0:19:59  lr: 0.000201  loss: 6.8630 (6.8815)  time: 1.0386  data: 0.0030  max mem: 8249
2021-03-10T13:17:53.482Z: [1,0]<stdout>:Epoch: [2]  [ 190/1251]  eta: 0:19:45  lr: 0.000201  loss: 6.8623 (6.8804)  time: 1.0409  data: 0.0028  max mem: 8249
2021-03-10T13:18:03.803Z: [1,0]<stdout>:Epoch: [2]  [ 200/1251]  eta: 0:19:29  lr: 0.000201  loss: 6.8623 (6.8798)  time: 1.0454  data: 0.0020  max mem: 8249
2021-03-10T13:18:14.249Z: [1,0]<stdout>:Epoch: [2]  [ 210/1251]  eta: 0:19:15  lr: 0.000201  loss: 6.8703 (6.8789)  time: 1.0382  data: 0.0024  max mem: 8249
2021-03-10T13:18:24.821Z: [1,0]<stdout>:Epoch: [2]  [ 220/1251]  eta: 0:19:01  lr: 0.000201  loss: 6.8581 (6.8779)  time: 1.0508  data: 0.0011  max mem: 8249
2021-03-10T13:18:35.464Z: [1,0]<stdout>:Epoch: [2]  [ 230/1251]  eta: 0:18:48  lr: 0.000201  loss: 6.8568 (6.8768)  time: 1.0599  data: 0.0007  max mem: 8249
2021-03-10T13:18:45.536Z: [1,0]<stdout>:Epoch: [2]  [ 240/1251]  eta: 0:18:33  lr: 0.000201  loss: 6.8443 (6.8749)  time: 1.0350  data: 0.0008  max mem: 8249
2021-03-10T13:18:56.198Z: [1,0]<stdout>:Epoch: [2]  [ 250/1251]  eta: 0:18:20  lr: 0.000201  loss: 6.8336 (6.8739)  time: 1.0361  data: 0.0013  max mem: 8249
2021-03-10T13:19:06.653Z: [1,0]<stdout>:Epoch: [2]  [ 260/1251]  eta: 0:18:07  lr: 0.000201  loss: 6.8366 (6.8725)  time: 1.0553  data: 0.0012  max mem: 8249
2021-03-10T13:19:17.180Z: [1,0]<stdout>:Epoch: [2]  [ 270/1251]  eta: 0:17:55  lr: 0.000201  loss: 6.8547 (6.8722)  time: 1.0490  data: 0.0004  max mem: 8249
2021-03-10T13:19:27.466Z: [1,0]<stdout>:Epoch: [2]  [ 280/1251]  eta: 0:17:42  lr: 0.000201  loss: 6.8517 (6.8711)  time: 1.0406  data: 0.0025  max mem: 8249
2021-03-10T13:19:37.910Z: [1,0]<stdout>:Epoch: [2]  [ 290/1251]  eta: 0:17:29  lr: 0.000201  loss: 6.8351 (6.8697)  time: 1.0360  data: 0.0048  max mem: 8249
2021-03-10T13:19:48.260Z: [1,0]<stdout>:Epoch: [2]  [ 300/1251]  eta: 0:17:16  lr: 0.000201  loss: 6.8368 (6.8689)  time: 1.0392  data: 0.0035  max mem: 8249
2021-03-10T13:19:58.663Z: [1,0]<stdout>:Epoch: [2]  [ 310/1251]  eta: 0:17:04  lr: 0.000201  loss: 6.8509 (6.8683)  time: 1.0369  data: 0.0021  max mem: 8249
2021-03-10T13:20:09.307Z: [1,0]<stdout>:Epoch: [2]  [ 320/1251]  eta: 0:16:52  lr: 0.000201  loss: 6.8419 (6.8670)  time: 1.0515  data: 0.0015  max mem: 8249
2021-03-10T13:20:19.698Z: [1,0]<stdout>:Epoch: [2]  [ 330/1251]  eta: 0:16:40  lr: 0.000201  loss: 6.8241 (6.8660)  time: 1.0512  data: 0.0006  max mem: 8249
2021-03-10T13:20:30.297Z: [1,0]<stdout>:Epoch: [2]  [ 340/1251]  eta: 0:16:28  lr: 0.000201  loss: 6.8314 (6.8650)  time: 1.0493  data: 0.0012  max mem: 8249
2021-03-10T13:20:40.767Z: [1,0]<stdout>:Epoch: [2]  [ 350/1251]  eta: 0:16:16  lr: 0.000201  loss: 6.8314 (6.8641)  time: 1.0534  data: 0.0038  max mem: 8249
2021-03-10T13:20:51.064Z: [1,0]<stdout>:Epoch: [2]  [ 360/1251]  eta: 0:16:04  lr: 0.000201  loss: 6.8063 (6.8622)  time: 1.0380  data: 0.0034  max mem: 8249
2021-03-10T13:21:01.273Z: [1,0]<stdout>:Epoch: [2]  [ 370/1251]  eta: 0:15:52  lr: 0.000201  loss: 6.8089 (6.8611)  time: 1.0249  data: 0.0018  max mem: 8249
2021-03-10T13:21:11.714Z: [1,0]<stdout>:Epoch: [2]  [ 380/1251]  eta: 0:15:40  lr: 0.000201  loss: 6.8153 (6.8599)  time: 1.0321  data: 0.0029  max mem: 8249
2021-03-10T13:21:22.110Z: [1,0]<stdout>:Epoch: [2]  [ 390/1251]  eta: 0:15:29  lr: 0.000201  loss: 6.8083 (6.8585)  time: 1.0416  data: 0.0049  max mem: 8249
2021-03-10T13:21:32.652Z: [1,0]<stdout>:Epoch: [2]  [ 400/1251]  eta: 0:15:17  lr: 0.000201  loss: 6.8251 (6.8577)  time: 1.0466  data: 0.0042  max mem: 8249
2021-03-10T13:21:43.074Z: [1,0]<stdout>:Epoch: [2]  [ 410/1251]  eta: 0:15:06  lr: 0.000201  loss: 6.8222 (6.8569)  time: 1.0481  data: 0.0015  max mem: 8249
2021-03-10T13:21:53.280Z: [1,0]<stdout>:Epoch: [2]  [ 420/1251]  eta: 0:14:54  lr: 0.000201  loss: 6.8168 (6.8559)  time: 1.0313  data: 0.0025  max mem: 8249
2021-03-10T13:22:03.987Z: [1,0]<stdout>:Epoch: [2]  [ 430/1251]  eta: 0:14:43  lr: 0.000201  loss: 6.8111 (6.8548)  time: 1.0455  data: 0.0050  max mem: 8249
2021-03-10T13:22:14.537Z: [1,0]<stdout>:Epoch: [2]  [ 440/1251]  eta: 0:14:32  lr: 0.000201  loss: 6.8212 (6.8542)  time: 1.0627  data: 0.0050  max mem: 8249
2021-03-10T13:22:24.913Z: [1,0]<stdout>:Epoch: [2]  [ 450/1251]  eta: 0:14:20  lr: 0.000201  loss: 6.8151 (6.8528)  time: 1.0462  data: 0.0038  max mem: 8249
2021-03-10T13:22:35.377Z: [1,0]<stdout>:Epoch: [2]  [ 460/1251]  eta: 0:14:09  lr: 0.000201  loss: 6.7994 (6.8517)  time: 1.0416  data: 0.0029  max mem: 8249
2021-03-10T13:22:37.350Z: [1,0]<stderr>:Traceback (most recent call last):
2021-03-10T13:22:37.352Z: [1,0]<stderr>:  File "main.py", line 422, in <module>
2021-03-10T13:22:37.395Z: [1,0]<stderr>:    main(args)
2021-03-10T13:22:37.395Z: [1,0]<stderr>:  File "main.py", line 381, in main
2021-03-10T13:22:37.396Z: [1,0]<stderr>:    set_training_mode=args.finetune == ''  # keep in eval mode during finetuning
2021-03-10T13:22:37.396Z: [1,0]<stderr>:  File "deit/engine.py", line 30, in train_one_epoch
2021-03-10T13:22:37.421Z: [1,0]<stderr>:Traceback (most recent call last):
2021-03-10T13:22:37.434Z: [1,0]<stderr>:    for samples, targets in metric_logger.log_every(data_loader, print_freq, header):
2021-03-10T13:22:37.434Z: [1,0]<stderr>:  File "deit/utils.py", line 136, in log_every
2021-03-10T13:22:37.442Z: [1,0]<stderr>:    for obj in iterable:
2021-03-10T13:22:37.442Z: [1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
2021-03-10T13:22:37.442Z: [1,0]<stderr>:    data = self._next_data()
2021-03-10T13:22:37.443Z: [1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1065, in _next_data
2021-03-10T13:22:37.443Z: [1,0]<stderr>:    return self._process_data(data)
2021-03-10T13:22:37.443Z: [1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
2021-03-10T13:22:37.443Z: [1,0]<stderr>:    data.reraise()
2021-03-10T13:22:37.443Z: [1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
2021-03-10T13:22:37.443Z: [1,0]<stderr>:    raise self.exc_type(msg)
2021-03-10T13:22:37.443Z: [1,0]<stderr>:OSError: Caught OSError in DataLoader worker process 3.
2021-03-10T13:22:37.443Z: [1,0]<stderr>:Original Traceback (most recent call last):
2021-03-10T13:22:37.443Z: [1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
2021-03-10T13:22:37.443Z: [1,0]<stderr>:    data = fetcher.fetch(index)
2021-03-10T13:22:37.444Z: [1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
2021-03-10T13:22:37.444Z: [1,0]<stderr>:    data = [self.dataset[idx] for idx in possibly_batched_index]
2021-03-10T13:22:37.444Z: [1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
2021-03-10T13:22:37.444Z: [1,0]<stderr>:    data = [self.dataset[idx] for idx in possibly_batched_index]
2021-03-10T13:22:37.444Z: [1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/datasets/folder.py", line 101, in __getitem__
2021-03-10T13:22:37.444Z: [1,0]<stderr>:    sample = self.loader(path)
2021-03-10T13:22:37.444Z: [1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/datasets/folder.py", line 147, in default_loader
2021-03-10T13:22:37.444Z: [1,0]<stderr>:    return pil_loader(path)
2021-03-10T13:22:37.444Z: [1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/datasets/folder.py", line 129, in pil_loader
2021-03-10T13:22:37.444Z: [1,0]<stderr>:    img = Image.open(f)
2021-03-10T13:22:37.444Z: [1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/PIL/Image.py", line 2622, in open
2021-03-10T13:22:37.444Z: [1,0]<stderr>:    % (filename if filename else fp))
2021-03-10T13:22:37.444Z: [1,0]<stderr>:OSError: cannot identify image file <_io.BufferedReader name='imagenet/raw-data/train/n01667778/n01667778_6494.JPEG'>
2021-03-10T13:22:37.445Z: [1,0]<stderr>:
2021-03-10T13:22:37.467Z: [1,0]<stderr>:  File "main.py", line 422, in <module>
2021-03-10T13:22:37.478Z: [1,0]<stderr>:    main(args)
2021-03-10T13:22:37.478Z: [1,0]<stderr>:  File "main.py", line 381, in main
2021-03-10T13:22:37.479Z: [1,0]<stderr>:    set_training_mode=args.finetune == ''  # keep in eval mode during finetuning
2021-03-10T13:22:37.479Z: [1,0]<stderr>:  File "deit/engine.py", line 30, in train_one_epoch
2021-03-10T13:22:37.480Z: [1,0]<stderr>:    for samples, targets in metric_logger.log_every(data_loader, print_freq, header):
2021-03-10T13:22:37.480Z: [1,0]<stderr>:  File "deit/utils.py", line 136, in log_every
2021-03-10T13:22:37.480Z: [1,0]<stderr>:    for obj in iterable:
2021-03-10T13:22:37.481Z: [1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 435, in __next__
2021-03-10T13:22:37.481Z: [1,0]<stderr>:    data = self._next_data()
2021-03-10T13:22:37.481Z: [1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1065, in _next_data
2021-03-10T13:22:37.481Z: [1,0]<stderr>:    return self._process_data(data)
2021-03-10T13:22:37.481Z: [1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 1111, in _process_data
2021-03-10T13:22:37.481Z: [1,0]<stderr>:    data.reraise()
2021-03-10T13:22:37.481Z: [1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torch/_utils.py", line 428, in reraise
2021-03-10T13:22:37.482Z: [1,0]<stderr>:    raise self.exc_type(msg)
2021-03-10T13:22:37.482Z: [1,0]<stderr>:OSError: Caught OSError in DataLoader worker process 3.
2021-03-10T13:22:37.482Z: [1,0]<stderr>:Original Traceback (most recent call last):
2021-03-10T13:22:37.482Z: [1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 198, in _worker_loop
2021-03-10T13:22:37.482Z: [1,0]<stderr>:    data = fetcher.fetch(index)
2021-03-10T13:22:37.482Z: [1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
2021-03-10T13:22:37.482Z: [1,0]<stderr>:    data = [self.dataset[idx] for idx in possibly_batched_index]
2021-03-10T13:22:37.482Z: [1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
2021-03-10T13:22:37.482Z: [1,0]<stderr>:    data = [self.dataset[idx] for idx in possibly_batched_index]
2021-03-10T13:22:37.482Z: [1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/datasets/folder.py", line 101, in __getitem__
2021-03-10T13:22:37.482Z: [1,0]<stderr>:    sample = self.loader(path)
2021-03-10T13:22:37.482Z: [1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/datasets/folder.py", line 147, in default_loader
2021-03-10T13:22:37.483Z: [1,0]<stderr>:    return pil_loader(path)
2021-03-10T13:22:37.483Z: [1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/torchvision-0.2.1-py3.6.egg/torchvision/datasets/folder.py", line 129, in pil_loader
2021-03-10T13:22:37.483Z: [1,0]<stderr>:    img = Image.open(f)
2021-03-10T13:22:37.483Z: [1,0]<stderr>:  File "/opt/conda/lib/python3.6/site-packages/PIL/Image.py", line 2622, in open
2021-03-10T13:22:37.483Z: [1,0]<stderr>:    % (filename if filename else fp))
2021-03-10T13:22:37.483Z: [1,0]<stderr>:OSError: cannot identify image file <_io.BufferedReader name='imagenet/raw-data/train/n01667778/n01667778_6494.JPEG'>

**Comment by Jxu-Thu** [comment]
I cannot figure out the reason. I checked that n01667778_6494.JPEG is not corrupt. 
I install by pip -r requirements.txt

**Comment by Jxu-Thu** [comment]
I have resolved the problem

**Comment by yazdanimehdi** [comment]
> I have resolved the problem

Can you please tell me how did you solve this problem? I have the exact same problem here.
